package com.techmentor.ConstTemplate;

public  interface EmailConstant {
String SUBJECT_THANKS_FOR_SUBSCRIBING = "Thanks for subscribing to TECHMENTOR";
String BODY__THANKS_FOR_SUBSCRIBING= "Hey there,\r\n"
		+ "\r\n"
		+ "First off, I’d like to extend a warm welcome and ‘thank you’ for subscribing to the TechMentor blog newsletter. I recognize that your time is valuable and I’m seriously flattered that you chose to join us.\r\n"
		+ "\r\n"
		+ "The TechMentor blog endeavors to send you only the best content, with actionable steps you can take to grow your business online and off. If we ever stray from that, just send me an email and I’ll do my damndest to get it straightened out.\r\n"
		+ "\r\n"
		+ "In the meantime, I’d love to hear from you about why you’ve subscribed to our list, and what you’re interested in learning about. So long as you reply to this email, I promise I will too.\r\n"
		+ "\r\n"
		+ "If you need anything, please feel free to give me a shout at 7loveindia@gmail.com .\r\n"
		+ "\r\n"
		+ "Again, welcome!\r\n"
		+ "\r\n"
		+ "Best,\r\n"
		+ "\r\n"
		+ "TechMentor";
String DYNAMIC_HTML = "<!DOCTYPE html>\r\n"
+"<meta http-equiv=\"Content-Type\"  content=\"text/html charset=UTF-8\" /> \r\n"
		+ "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n"
		+ "<html xmlns:fb=\"https://www.facebook.com/2008/fbml\" xmlns:og=\"http://opengraph.org/schema/\">\r\n"
		+ "\r\n"
		+ "<head>\r\n"
		+ "\r\n"
		+ "  <meta property=\"fb:page_id\" content=\"43929265776\" />\r\n"
		+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n"
		+ "  <meta name=\"twitter:image:src\" content=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "  <meta name=\"twitter:description\" content=\"At MailChimp, we love to show our work—in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it’ll help you do the same.\">\r\n"
		+ "  <meta name=\"twitter:title\" content=\"The UX Reader\">\r\n"
		+ "  <meta name=\"twitter:card\" content=\"summary_large_image\">\r\n"
		+ "  <meta property=\"og:type\" content=\"article\">\r\n"
		+ "  <meta property=\"og:description\" content=\"At MailChimp, we love to show our work—in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it’ll help you do the same.\">\r\n"
		+ "  <meta property=\"og:image\" content=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "  <meta property=\"og:title\" content=\"The UX Reader\">\r\n"
		+ "  <meta property=\"og:url\" content=\"http://eepurl.com/8Dzmj\">\r\n"
		+ "  <meta name=\"twitter:image:src\" content=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "  <meta name=\"twitter:description\" content=\"At MailChimp, we love to show our work—in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it’ll help you do the same.\">\r\n"
		+ "  <meta name=\"twitter:title\" content=\"The UX Reader\">\r\n"
		+ "  <meta name=\"twitter:card\" content=\"summary_large_image\">\r\n"
		+ "  <meta property=\"og:description\" content=\"At MailChimp, we love to show our work—in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it’ll help you do the same.\">\r\n"
		+ "  <meta property=\"og:image\" content=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "  <meta property=\"og:title\" content=\"The UX Reader\">\r\n"
		+ "  <meta property=\"og:url\" content=\"http://eepurl.com/8Dzmj\">\r\n"
		+ "  <meta name=\"twitter:image:src\" content=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "  <meta name=\"twitter:description\" content=\"At MailChimp, we love to show our work—in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it’ll help you do the same.\">\r\n"
		+ "  <meta name=\"twitter:title\" content=\"The UX Reader\">\r\n"
		+ "  <meta name=\"twitter:card\" content=\"summary_large_image\">\r\n"
		+ "  <meta property=\"og:description\" content=\"At MailChimp, we love to show our work—in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it’ll help you do the same.\">\r\n"
		+ "  <meta property=\"og:image\" content=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "  <meta property=\"og:title\" content=\"The UX Reader\">\r\n"
		+ "  <meta property=\"og:url\" content=\"http://eepurl.com/8Dzmj\">\r\n"
		+ "  <meta charset=\"UTF-8\">\r\n"
		+ "  <meta name=\"viewport\" content=\"width=device-width\">\r\n"
		+ "  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
		+ "  <title>The UX Reader</title>\r\n"
		+ "  <style type=\"text/css\">\r\n"
		+ "    /* RESET STYLES */\r\n"
		+ "    			p{margin:1em 0;}\r\n"
		+ "    			table{border-collapse:collapse; table-layout:fixed;}\r\n"
		+ "    			img, a img{border:0; height:auto; outline:none; text-decoration:none;}\r\n"
		+ "    			h1, h2, h3, h4, h5, h6{display:block !important; margin:0 !important; padding:0 !important;}\r\n"
		+ "    			body, #bodyTable, #bodyCell{height:100% !important; margin:0; padding:0; width:100% !important;}\r\n"
		+ "    \r\n"
		+ "    			/* CLIENT-SPECIFIC STYLES */\r\n"
		+ "    			img{-ms-interpolation-mode: bicubic;} /* Force IE to smoothly render resized images. */\r\n"
		+ "    			#outlook a{padding:0;} /* Force Outlook 2007 and up to provide a \"view in browser\" message. */\r\n"
		+ "    			table{mso-table-lspace:0pt; mso-table-rspace:0pt;} /* Remove spacing between tables in Outlook 2007 and up. */\r\n"
		+ "    			.ReadMsgBody{width:100%;} .ExternalClass{width:100%;} /* Force Outlook.com to display emails at full width. */\r\n"
		+ "    			p, a, li, td, blockquote{mso-line-height-rule:exactly;} /* Force Outlook to render line heights as they're originally set. */\r\n"
		+ "    			a[href^=\"tel\"], a[href^=\"sms\"]{color:inherit; cursor:default; text-decoration:none;} /* Force mobile devices to inherit declared link styles. */\r\n"
		+ "    			p, a, li, td, body, table, blockquote{-ms-text-size-adjust:100%; -webkit-text-size-adjust:100%;} /* Prevent Windows- and Webkit-based mobile platforms from changing declared text sizes. */\r\n"
		+ "    			.ExternalClass, .ExternalClass p, .ExternalClass td, .ExternalClass div, .ExternalClass span, .ExternalClass font{line-height:100%;} /* Force Outlook.com to display line heights normally. */\r\n"
		+ "    \r\n"
		+ "    			/* CONTENT STYLES */\r\n"
		+ "    			@media screen{\r\n"
		+ "    				@font-face{\r\n"
		+ "    					font-family:'Merriweather';\r\n"
		+ "    					font-style:normal;\r\n"
		+ "    					font-weight:400;\r\n"
		+ "    					src:local('Merriweather'),\r\n"
		+ "    						url(https://fonts.gstatic.com/s/merriweather/v8/RFda8w1V0eDZheqfcyQ4EKRDOzjiPcYnFooOUGCOsRk.woff) format('woff');\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				@font-face{\r\n"
		+ "    					font-family:'Source Sans Pro';\r\n"
		+ "    					font-style:normal;\r\n"
		+ "    					font-weight:400;\r\n"
		+ "    					src:local('Source Sans Pro'),\r\n"
		+ "    						local('SourceSansPro-Regular'),\r\n"
		+ "    						url(https://fonts.gstatic.com/s/sourcesanspro/v9/ODelI1aHBYDBqgeIAH2zlNHq-FFgoDNV3GTKpHwuvtI.woff) format('woff');\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				@font-face{\r\n"
		+ "    					font-family:'Source Sans Pro';\r\n"
		+ "    					font-style:normal;\r\n"
		+ "    					font-weight:700;\r\n"
		+ "    					src:local('Source Sans Pro Bold'),\r\n"
		+ "    						local('SourceSansPro-Bold'),\r\n"
		+ "    						url(https://fonts.gstatic.com/s/sourcesanspro/v9/toadOcfmlt9b38dHJxOBGIqjGYJUyOXcBwUQbRaNH6c.woff) format('woff');\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				div[class=\"previewCarousel\"]{height:315px; overflow:hidden; position:relative; width:100%;}\r\n"
		+ "    \r\n"
		+ "    				table[class=\"previewItem\"]{\r\n"
		+ "    					-webkit-animation-name:previewCarousel;\r\n"
		+ "    					-webkit-animation-delay:0s;\r\n"
		+ "    					-webkit-animation-direction:normal;\r\n"
		+ "    					-webkit-animation-duration:25s;\r\n"
		+ "    					-webkit-animation-fill-mode:none;\r\n"
		+ "    					-webkit-animation-iteration-count:infinite;\r\n"
		+ "    					-webkit-animation-play-state:running;\r\n"
		+ "    					-webkit-animation-timing-function:linear;\r\n"
		+ "    					-moz-animation-name:previewCarousel;\r\n"
		+ "    					-moz-animation-delay:0s;\r\n"
		+ "    					-moz-animation-direction:normal;\r\n"
		+ "    					-moz-animation-duration:25s;\r\n"
		+ "    					-moz-animation-fill-mode:none;\r\n"
		+ "    					-moz-animation-iteration-count:infinite;\r\n"
		+ "    					-moz-animation-play-state:running;\r\n"
		+ "    					-moz-animation-timing-function:linear;\r\n"
		+ "    					-ms-animation-name:previewCarousel;\r\n"
		+ "    					-ms-animation-delay:0s;\r\n"
		+ "    					-ms-animation-direction:normal;\r\n"
		+ "    					-ms-animation-duration:25s;\r\n"
		+ "    					-ms-animation-fill-mode:none;\r\n"
		+ "    					-ms-animation-iteration-count:infinite;\r\n"
		+ "    					-ms-animation-play-state:running;\r\n"
		+ "    					-ms-animation-timing-function:linear;\r\n"
		+ "    					-o-animation-name:previewCarousel;\r\n"
		+ "    					-o-animation-delay:0s;\r\n"
		+ "    					-o-animation-direction:normal;\r\n"
		+ "    					-o-animation-duration:25s;\r\n"
		+ "    					-o-animation-fill-mode:none;\r\n"
		+ "    					-o-animation-iteration-count:infinite;\r\n"
		+ "    					-o-animation-play-state:running;\r\n"
		+ "    					-o-animation-timing-function:linear;\r\n"
		+ "    					animation-name:previewCarousel;\r\n"
		+ "    					animation-delay:0s;\r\n"
		+ "    					animation-direction:normal;\r\n"
		+ "    					animation-duration:25s;\r\n"
		+ "    					animation-fill-mode:none;\r\n"
		+ "    					animation-iteration-count:infinite;\r\n"
		+ "    					animation-play-state:running;\r\n"
		+ "    					animation-timing-function:linear;\r\n"
		+ "    					position:absolute;\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				table[class=\"previewItem\"]:nth-child(2){\r\n"
		+ "    					-webkit-animation-delay:5s;\r\n"
		+ "    					-moz-animation-delay:5s;\r\n"
		+ "    					-ms-animation-delay:5s;\r\n"
		+ "    					-o-animation-delay:5s;\r\n"
		+ "    					animation-delay:5s;\r\n"
		+ "    					opacity:0;\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				table[class=\"previewItem\"]:nth-child(3){\r\n"
		+ "    					-webkit-animation-delay:10s;\r\n"
		+ "    					-moz-animation-delay:10s;\r\n"
		+ "    					-ms-animation-delay:10s;\r\n"
		+ "    					-o-animation-delay:10s;\r\n"
		+ "    					animation-delay:10s;\r\n"
		+ "    					opacity:0;\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				table[class=\"previewItem\"]:nth-child(4){\r\n"
		+ "    					-webkit-animation-delay:15s;\r\n"
		+ "    					-moz-animation-delay:15s;\r\n"
		+ "    					-ms-animation-delay:15s;\r\n"
		+ "    					-o-animation-delay:15s;\r\n"
		+ "    					animation-delay:15s;\r\n"
		+ "    					opacity:0;\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				table[class=\"previewItem\"]:nth-child(5){\r\n"
		+ "    					-webkit-animation-delay:20s;\r\n"
		+ "    					-moz-animation-delay:20s;\r\n"
		+ "    					-ms-animation-delay:20s;\r\n"
		+ "    					-o-animation-delay:20s;\r\n"
		+ "    					animation-delay:20s;\r\n"
		+ "    					opacity:0;\r\n"
		+ "    				}\r\n"
		+ "    \r\n"
		+ "    				td[class=\"previewItemTitle\"]{display:none !important; visibility:hidden !important; width:0 !important;}\r\n"
		+ "    \r\n"
		+ "    				@-webkit-keyframes previewCarousel{0%, 30%, 100%{opacity:0;} 5%, 25%{opacity:1;}}\r\n"
		+ "    				@-moz-keyframes previewCarousel{0%, 30%, 100%{opacity:0;} 5%, 25%{opacity:1;}}\r\n"
		+ "    				@-ms-keyframes previewCarousel{0%, 30%, 100%{opacity:0;} 5%, 25%{opacity:1;}}\r\n"
		+ "    				@keyframes previewCarousel{0%, 30%, 100%{opacity:0;} 5%, 25%{opacity:1;}}\r\n"
		+ "    			}\r\n"
		+ "    \r\n"
		+ "    			/* MOBILE STYLES*/\r\n"
		+ "    			@media screen and (max-width:768px){\r\n"
		+ "    				div[class=\"previewCarousel\"]{height:335px !important;}\r\n"
		+ "    				div[class=\"centerWrap\"]{float:left !important; max-width:50% !important;}\r\n"
		+ "    				td[class=\"previewItemImage\"] img{height:auto !important; max-width:180px !important; width:100% !important;}\r\n"
		+ "    			}\r\n"
		+ "    \r\n"
		+ "    			@media screen and (max-width:480px){\r\n"
		+ "    				h2{font-size:20px !important; line-height:26px !important;}\r\n"
		+ "    				/*div[class=\"previewCarousel\"]{height:330px;}*/\r\n"
		+ "    				div[class=\"centerWrap\"]{float:none !important; max-width:100% !important;}\r\n"
		+ "    				td[class=\"previewItemTitle\"]{display:block !important; padding-top:0 !important; padding-bottom:20px !important; visibility:visible !important; width:100% !important;}\r\n"
		+ "    				td[class=\"previewItemContent\"]{padding-top:0 !important; padding-bottom:40px !important; text-align:center !important; width:90% !important;}\r\n"
		+ "    				td[class=\"previewItemContent\"] h4{text-align:center !important;}\r\n"
		+ "    				td[class=\"previewItemImage\"]{display:none !important; visibility:hidden !important; width:0 !important;}\r\n"
		+ "    				table[class=\"mobileExpand\"]{max-width:90% !important;}\r\n"
		+ "    			}\r\n"
		+ "  </style>\r\n"
		+ "  <!--[if gte mso 9]>\r\n"
		+ "		<style type=\"text/css\">\r\n"
		+ "			.previewItemContent{padding-top:0px; padding-left:20px;}\r\n"
		+ "		</style>\r\n"
		+ "		<![endif]-->\r\n"
		+ "  <script type=\"text/javascript\">\r\n"
		+ "    var gaJsHost = ((\"https:\" == document.location.protocol) ? \"https://ssl.\" : \"http://www.\");\r\n"
		+ "            document.write(unescape(\"%3Cscript src='\" + gaJsHost + \"google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E\"));\r\n"
		+ "  </script>\r\n"
		+ "  <script type=\"text/javascript\">\r\n"
		+ "    try {\r\n"
		+ "                var _gaq = _gaq || [];\r\n"
		+ "                _gaq.push([\"_setAccount\", \"UA-30749140-2\"]);\r\n"
		+ "                _gaq.push([\"_setDomainName\", \".campaign-archive.com\"]);\r\n"
		+ "                _gaq.push([\"_trackPageview\"]);\r\n"
		+ "                _gaq.push([\"_setAllowLinker\", true]);\r\n"
		+ "            } catch(err) {console.log(err);}\r\n"
		+ "  </script>\r\n"
		+ "  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js\"></script>\r\n"
		+ "  <script src=\"http://us5.campaign-archive1.com/js/mailchimp/fancyzoom.mc.js\"></script>\r\n"
		+ "  <script type=\"text/javascript\">\r\n"
		+ "    function incrementFacebookLikeCount() {\r\n"
		+ "        var current = parseInt($('#campaign-fb-like-btn span').html());\r\n"
		+ "        $('#campaign-fb-like-btn span').fadeOut().html(++current).fadeIn();\r\n"
		+ "    }\r\n"
		+ "\r\n"
		+ "    function getUrlParams(str) {\r\n"
		+ "        var vars = {}, hash;\r\n"
		+ "        if (!str) return vars;\r\n"
		+ "        var hashes = str.slice(str.indexOf('?') + 1).split('&');\r\n"
		+ "        for(var i = 0; i < hashes.length; i++) {\r\n"
		+ "            hash = hashes[i].split('=');\r\n"
		+ "            vars[hash[0]] = hash[1];\r\n"
		+ "        }\r\n"
		+ "        return vars;\r\n"
		+ "    }\r\n"
		+ "    \r\n"
		+ "    function setupSocialSharingStuffs() {\r\n"
		+ "        var numSocialElems = $('a[rel=socialproxy]').length;\r\n"
		+ "        var numSocialInitialized = 0;\r\n"
		+ "        var urlParams = getUrlParams(window.document.location.href);\r\n"
		+ "        var paramsToCopy = {'e':true, 'eo':true};\r\n"
		+ "        $('a[rel=socialproxy]').each(function() {\r\n"
		+ "            var href = $(this).attr('href');\r\n"
		+ "            var newHref = decodeURIComponent(href.match(/socialproxy=(.*)/)[1]);\r\n"
		+ "            // for facebook insanity to work well, it needs to all be run against just campaign-archive\r\n"
		+ "            newHref = newHref.replace(/campaign-archive(\\d)/gi, 'campaign-archive');\r\n"
		+ "            var newHrefParams = getUrlParams(newHref);\r\n"
		+ "            for(var param in urlParams) {\r\n"
		+ "                if ((param in paramsToCopy) && !(param in newHrefParams)) {\r\n"
		+ "                    newHref += '&' + param + '=' + urlParams[param];\r\n"
		+ "                }\r\n"
		+ "            }\r\n"
		+ "            $(this).attr('href', newHref);\r\n"
		+ "            if (href.indexOf('facebook-comment') !== -1) {\r\n"
		+ "                $(this).fancyZoom({\"zoom_id\": \"social-proxy\", \"width\":620, \"height\":450, \"iframe_height\": 450});\r\n"
		+ "            } else {\r\n"
		+ "                $(this).fancyZoom({\"zoom_id\": \"social-proxy\", \"width\":500, \"height\":200, \"iframe_height\": 500});\r\n"
		+ "            }\r\n"
		+ "            numSocialInitialized++;\r\n"
		+ "                    });\r\n"
		+ "    }\r\n"
		+ "	if (window.top!=window.self){\r\n"
		+ "        $(function() {\r\n"
		+ "          var iframeOffset = $(\"#archive\", window.parent.document).offset();\r\n"
		+ "          $(\"a\").each(function () {\r\n"
		+ "              var link = $(this);\r\n"
		+ "              var href = link.attr(\"href\");\r\n"
		+ "              if (href && href[0] == \"#\") {\r\n"
		+ "                  var name = href.substring(1);\r\n"
		+ "                  $(this).click(function () {\r\n"
		+ "                      var nameElement = $(\"[name='\" + name + \"']\");\r\n"
		+ "                      var idElement = $(\"#\" + name);\r\n"
		+ "                      var element = null;\r\n"
		+ "                      if (nameElement.length > 0) {\r\n"
		+ "                          element = nameElement;\r\n"
		+ "                      } else if (idElement.length > 0) {\r\n"
		+ "                          element = idElement;\r\n"
		+ "                      }\r\n"
		+ "         \r\n"
		+ "                      if (element) {\r\n"
		+ "                          var offset = element.offset();\r\n"
		+ "                          var height = element.height();\r\n"
		+ "                          //3 is totally arbitrary, but seems to work best.\r\n"
		+ "                          window.parent.scrollTo(offset.left, (offset.top + iframeOffset.top - (height*3)) );\r\n"
		+ "                      }\r\n"
		+ "         \r\n"
		+ "                      return false;\r\n"
		+ "                  });\r\n"
		+ "              }\r\n"
		+ "          });\r\n"
		+ "        });\r\n"
		+ "    }\r\n"
		+ "  </script>\r\n"
		+ "  <script type=\"text/javascript\">\r\n"
		+ "    $(document).ready(function() {\r\n"
		+ "                setupSocialSharingStuffs();\r\n"
		+ "            });\r\n"
		+ "  </script>\r\n"
		+ "  <style type=\"text/css\">\r\n"
		+ "    /* Facebook/Google+ Modals */\r\n"
		+ "            #social-proxy { background:#fff; -webkit-box-shadow: 4px 4px 8px 2px rgba(0,0,0,.2); box-shadow: 4px 4px 8px 2px rgba(0,0,0,.2); padding-bottom:35px; z-index:1000; }\r\n"
		+ "            #social-proxy_close { display:block; position:absolute; top:0; right:0; height:30px; width:32px; background:transparent url(http://cdn-images.mailchimp.com/awesomebar-sprite.png) 0 -200px; text-indent:-9999px; outline:none; font-size:1px; }\r\n"
		+ "            #social-proxy_close:hover { background-position:0 -240px; }\r\n"
		+ "            body { padding-bottom:50px !important; }\r\n"
		+ "  </style>\r\n"
		+ "</head>\r\n"
		+ "\r\n"
		+ "<body style=\"background-color:#7F828E;\">\r\n"
		+ "  <div itemscope=\"\" itemtype=\"http://schema.org/EmailMessage\">\r\n"
		+ "    <div itemprop=\"publisher\" itemscope=\"\" itemtype=\"http://schema.org/Organization\">\r\n"
		+ "      <meta itemprop=\"name\" content=\"MailChimp UX\">\r\n"
		+ "      <link itemprop=\"url\" content=\"http://mailchimp.com\">\r\n"
		+ "    </div>\r\n"
		+ "    <div itemprop=\"about\" itemscope=\"\" itemtype=\"http://schema.org/Offer\">\r\n"
		+ "      <link itemprop=\"image\" href=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "    </div>\r\n"
		+ "  </div>\r\n"
		+ "  <div itemscope=\"\" itemtype=\"http://schema.org/EmailMessage\">\r\n"
		+ "    <div itemprop=\"publisher\" itemscope=\"\" itemtype=\"http://schema.org/Organization\">\r\n"
		+ "      <meta itemprop=\"name\" content=\"MailChimp UX\">\r\n"
		+ "      <link itemprop=\"url\" content=\"http://mailchimp.com\">\r\n"
		+ "    </div>\r\n"
		+ "    <div itemprop=\"about\" itemscope=\"\" itemtype=\"http://schema.org/Offer\">\r\n"
		+ "      <link itemprop=\"image\" href=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "    </div>\r\n"
		+ "  </div>\r\n"
		+ "  <div itemscope=\"\" itemtype=\"http://schema.org/EmailMessage\">\r\n"
		+ "    <div itemprop=\"publisher\" itemscope=\"\" itemtype=\"http://schema.org/Organization\">\r\n"
		+ "      <meta itemprop=\"name\" content=\"MailChimp UX\">\r\n"
		+ "      <link itemprop=\"url\" content=\"http://mailchimp.com\">\r\n"
		+ "    </div>\r\n"
		+ "    <div itemprop=\"about\" itemscope=\"\" itemtype=\"http://schema.org/Offer\">\r\n"
		+ "      <link itemprop=\"image\" href=\"https://gallery.mailchimp.com/7e093c5cf4/images/338a8646-49db-4219-bab0-2d4527a96295.png\">\r\n"
		+ "    </div>\r\n"
		+ "  </div>\r\n"
		+ "  <center>\r\n"
		+ "    <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"100%\" width=\"100%\" id=\"bodyTable\" style=\"background-color:#7F828E;\">\r\n"
		+ "      <tr>\r\n"
		+ "        <td align=\"center\" valign=\"top\" id=\"bodyCell\" style=\"background-color:#7F828E;\">\r\n"
		+ "          <table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\" id=\"emailHeader\" style=\"background-color:#D3D7DC;\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"emailContainer\" style=\"max-width:640px;\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td align=\"center\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"480\">\r\n"
		+ "												<tr>\r\n"
		+ "												<td align=\"center\" valign=\"top\">\r\n"
		+ "												<![endif]-->\r\n"
		+ "                      <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\" class=\"mobileExpand\" style=\"max-width:65%;\">\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"padding-top:20px;\">\r\n"
		+ "                            <a href=\"http://theuxreader.com/\" target=\"_blank\"><img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/ux_reader_logo.png\" width=\"150\" style=\"height:auto !important;\"></a>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" class=\"headerContent\" style=\"color:#5A5D67; font-family:Merriweather, Georgia, 'Times New Roman', Times, serif; font-size:16px; line-height:26px; padding-top:30px;\">\r\n"
		+ "                            Insights on process and purpose from MailChimp&rsquo;s user experience team.\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\">\r\n"
		+ "                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"emailButton\" style=\"background-color:#7F828E;\">\r\n"
		+ "                              <tr>\r\n"
		+ "                                <td align=\"center\" valign=\"middle\" class=\"buttonContent\">\r\n"
		+ "                                  <a href=\"http://theuxreader.com/products/the-ux-reader-ebook\" target=\"_blank\" style=\"border-top:10px solid #7F828E; border-right:20px solid #7F828E; border-bottom:10px solid #7F828E; border-left:20px solid #7F828E; color:#FFFFFF; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:18px; text-decoration:none;\">BUY THE EBOOK</a>\r\n"
		+ "                                </td>\r\n"
		+ "                              </tr>\r\n"
		+ "                            </table>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-bottom:20px; text-align:center;\">\r\n"
		+ "                            $5, proceeds benefit <a href=\"http://www.railsbridge.org/\" target=\"_blank\" style=\"color:#7F828E; text-decoration:underline;\">RailsBridge</a>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                      </table>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												</td>\r\n"
		+ "												</tr>\r\n"
		+ "												</table>\r\n"
		+ "												<![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"25\" width=\"100%\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td background=\"http://cdn-images.mailchimp.com/template_images/ux_reader/grey_to_red.jpg\" bgcolor=\"#D3D7DC\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "										  <v:rect xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\" style=\"mso-width-percent:1000;height:25px;\">\r\n"
		+ "											<v:fill type=\"tile\" src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/grey_to_red.jpg\" color=\"#D3D7DC\" />\r\n"
		+ "											<v:textbox inset=\"0,0,0,0\">\r\n"
		+ "										  <![endif]-->\r\n"
		+ "                      <div>\r\n"
		+ "                      </div>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "											</v:textbox>\r\n"
		+ "										  </v:rect>\r\n"
		+ "										  <![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\" id=\"emailBody\" style=\"background-color:#FF8578;\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"emailContainer\" style=\"max-width:640px;\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td align=\"center\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"480\">\r\n"
		+ "												<tr>\r\n"
		+ "												<td align=\"center\" valign=\"top\">\r\n"
		+ "												<![endif]-->\r\n"
		+ "                      <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\" class=\"mobileExpand\" style=\"max-width:65%;\">\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" class=\"bodyContent\" style=\"color:#FFFFFF; font-family:Merriweather, Georgia, 'Times New Roman', Times, serif; font-size:16px; line-height:26px; padding-top:20px; padding-bottom:20px;\">\r\n"
		+ "                            <h2 style=\"font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:26px; font-weight:600; line-height:36px;\">About the book</h2>\r\n"
		+ "                            <br> At MailChimp, we love to show our work&mdash;in part because it helps us get better at what we do. This book is the embodiment of our quest to reflect, refine, and grow. We made it in hopes it&rsquo;ll help you do the\r\n"
		+ "                            same.\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                      </table>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												</td>\r\n"
		+ "												</tr>\r\n"
		+ "												</table>\r\n"
		+ "												<![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"25\" width=\"100%\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td background=\"http://cdn-images.mailchimp.com/template_images/ux_reader/red_to_white.jpg\" bgcolor=\"#D3D7DC\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "										  <v:rect xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\" style=\"mso-width-percent:1000;height:25px;\">\r\n"
		+ "											<v:fill type=\"tile\" src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/red_to_white.jpg\" color=\"#D3D7DC\" />\r\n"
		+ "											<v:textbox inset=\"0,0,0,0\">\r\n"
		+ "										  <![endif]-->\r\n"
		+ "                      <div>\r\n"
		+ "                      </div>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "											</v:textbox>\r\n"
		+ "										  </v:rect>\r\n"
		+ "										  <![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\" id=\"email\" style=\"background-color:#FFFFFF;\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"emailContainer\" style=\"max-width:640px;\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td align=\"center\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"640\">\r\n"
		+ "												<tr>\r\n"
		+ "												<td align=\"center\" valign=\"top\">\r\n"
		+ "												<![endif]-->\r\n"
		+ "                      <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\" class=\"mobileExpand\" style=\"max-width:85%;\">\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"padding-top:20px;\">\r\n"
		+ "                            <h2 style=\"font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:26px; font-weight:600; line-height:36px;\">What's inside</h2>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"padding-bottom:0;\">\r\n"
		+ "                            <div class=\"previewCarousel\">\r\n"
		+ "                              <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"previewItem\" style=\"background-color:#FFFFFF;\">\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"top\" class=\"previewItemTitle\" style=\"padding-bottom:20px;\">\r\n"
		+ "                                    <h3 style=\"color:#D83B25 !important; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:16px;\">DEVELOPMENT</h3>\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"middle\">\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"640\">\r\n"
		+ "																			<tr>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"200\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:220px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td align=\"center\" valign=\"top\" class=\"previewItemImage\" style=\"padding-top:14px; padding-bottom:20px;\">\r\n"
		+ "                                            <img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/img_development.png\" width=\"200\" style=\"height:auto !important;\">\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"440\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:300px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td valign=\"middle\" class=\"previewItemContent\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-top:0; padding-right:0; padding-bottom:40px; text-align:left;\">\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0; text-align:left;\">Building a System for Responsive Email</h4> Fabio Carneiro\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0; text-align:left;\">Tightening Type and Relative Font Sizing</h4> Mardav Wala\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0; text-align:left;\">Creativity in Front-End Development</h4> Jason Beaird\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0; text-align:left;\">Release Cycles and Roadmaps</h4> Federico Holgado\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			</tr>\r\n"
		+ "																			</table>\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                              </table>\r\n"
		+ "                              <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"previewItem\" style=\"background-color:#FFFFFF;\">\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"top\" class=\"previewItemTitle\" style=\"padding-bottom:20px;\">\r\n"
		+ "                                    <h3 style=\"color:#26A8D5 !important; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:16px;\">DESIGN</h3>\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"middle\">\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"640\">\r\n"
		+ "																			<tr>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"200\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:220px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td align=\"center\" valign=\"top\" class=\"previewItemImage\" style=\"padding-bottom:20px;\">\r\n"
		+ "                                            <img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/img_design.png\" width=\"200\" style=\"height:auto !important;\">\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"440\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:300px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td valign=\"middle\" class=\"previewItemContent\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-top:30px; padding-right:0; padding-bottom:20px; text-align:left;\">\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Why You Should Sketch, and How</h4> Federico Holgado\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Evolution of a Pattern Library</h4> Jason Beaird\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Building a Better Pattern Library</h4> Federico Holdgado\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">High Five for SVGs</h4> Caleb Andrews, Alvaro Sanchez\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			</tr>\r\n"
		+ "																			</table>\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                              </table>\r\n"
		+ "                              <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"previewItem\" style=\"background-color:#FFFFFF;\">\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"top\" class=\"previewItemTitle\" style=\"padding-top:20px; padding-bottom:20px;\">\r\n"
		+ "                                    <h3 style=\"color:#339868 !important; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:16px;\">COLLABORATION</h3>\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"middle\">\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"640\">\r\n"
		+ "																			<tr>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"200\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:220px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td align=\"center\" valign=\"top\" class=\"previewItemImage\" style=\"padding-top:5px; padding-bottom:20px;\">\r\n"
		+ "                                            <img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/img_collaboration.png\" width=\"200\" style=\"height:auto !important;\">\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"440\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:300px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td valign=\"middle\" class=\"previewItemContent\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-top:0; padding-bottom:20px; text-align:left;\">\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0; margin:0 !important; padding:0 !important;\">Building a UX Team</h4> Aarron Walter\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Collaboration by Design</h4> Aarron Walter\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">All Hands on Deck</h4> June Lee\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Asking for Help</h4> Fernando Godina\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">On Good Terms</h4> Gregg Bernstein\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			</tr>\r\n"
		+ "																			</table>\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                              </table>\r\n"
		+ "                              <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"previewItem\" style=\"background-color:#FFFFFF;\">\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"top\" class=\"previewItemTitle\" style=\"padding-top:20px; padding-bottom:20px;\">\r\n"
		+ "                                    <h3 style=\"color:#4B4697 !important; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:16px;\">RESEARCH</h3>\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"middle\">\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"640\">\r\n"
		+ "																			<tr>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"200\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:220px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td align=\"center\" valign=\"top\" class=\"previewItemImage\" style=\"padding-bottom:20px;\">\r\n"
		+ "                                            <img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/img_research.png\" width=\"200\" style=\"height:auto !important;\">\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"440\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:300px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td valign=\"middle\" class=\"previewItemContent\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-top:6px; padding-bottom:20px; text-align:left;\">\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Radicalizing Data</h4> Gregg Bernstein\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Sharing Research by Every Means Necessary</h4> Laurissa Wolfram-Hvass\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">We Sorted 506,000 Data Points and Lived to Tell the Tale</h4> Fernando Godina,\r\n"
		+ "                                            <br> Laurissa Wolfram-Hvass\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">The Open-Minded Interview</h4> Steph Troeth\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			</tr>\r\n"
		+ "																			</table>\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                              </table>\r\n"
		+ "                              <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"previewItem\" style=\"background-color:#FFFFFF;\">\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"top\" class=\"previewItemTitle\" style=\"padding-top:20px; padding-bottom:20px;\">\r\n"
		+ "                                    <h3 style=\"color:#FFBE11 !important; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:16px;\">REFINEMENT</h3>\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                                <tr>\r\n"
		+ "                                  <td align=\"center\" valign=\"middle\">\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"640\">\r\n"
		+ "																			<tr>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"200\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:220px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td align=\"center\" valign=\"top\" class=\"previewItemImage\" style=\"padding-top:10px; padding-bottom:20px;\">\r\n"
		+ "                                            <img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/img_refinement.png\" width=\"200\" style=\"height:auto !important;\">\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			<td align=\"center\" valign=\"top\" width=\"440\">\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                    <div class=\"centerWrap\" style=\"display:inline-block; max-width:300px; vertical-align:top; width:100%;\">\r\n"
		+ "                                      <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                                        <tr>\r\n"
		+ "                                          <td valign=\"middle\" class=\"previewItemContent\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-top:0; padding-bottom:40px; text-align:left;\">\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Iteration and the Feature/Refinement Balance</h4> Jason Beaird\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Making MailChimp More Accessible</h4> Mardav Wala\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Fixing a Leaky Funnel with Google Analytics</h4> Allison Urban\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Learning from Our Mistakes</h4> Tyrick Christian\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <br>\r\n"
		+ "                                            <h4 style=\"color:#000000 !important; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:20px; margin:0; padding:0;\">Refining via Redesign</h4> Tyrick Christian\r\n"
		+ "                                          </td>\r\n"
		+ "                                        </tr>\r\n"
		+ "                                      </table>\r\n"
		+ "                                    </div>\r\n"
		+ "                                    <!--[if gte mso 9]>\r\n"
		+ "																			</td>\r\n"
		+ "																			</tr>\r\n"
		+ "																			</table>\r\n"
		+ "																			<![endif]-->\r\n"
		+ "                                  </td>\r\n"
		+ "                                </tr>\r\n"
		+ "                              </table>\r\n"
		+ "                            </div>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"padding-top:0;\">\r\n"
		+ "                            <img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/ux_reader_hr.png\" width=\"600\" style=\"height:auto !important; width:100% !important;\">\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"padding-top:20px; padding-bottom:20px;\">\r\n"
		+ "                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" class=\"emailButton\" style=\"background-color:#FF8578;\">\r\n"
		+ "                              <tr>\r\n"
		+ "                                <td align=\"center\" valign=\"middle\" class=\"buttonContent\">\r\n"
		+ "                                  <a href=\"http://theuxreader.com/products/the-ux-reader-ebook\" target=\"_blank\" style=\"border-top:10px solid #FF8578; border-right:20px solid #FF8578; border-bottom:10px solid #FF8578; border-left:20px solid #FF8578; color:#FFFFFF; display:block; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; font-weight:600; line-height:18px; text-decoration:none;\">BUY THE EBOOK</a>\r\n"
		+ "                                </td>\r\n"
		+ "                              </tr>\r\n"
		+ "                            </table>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"color:#7F828E; font-family:'Source Sans Pro', 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size:16px; line-height:16px; padding-bottom:20px; text-align:center;\">\r\n"
		+ "                            $5, proceeds benefit <a href=\"http://www.railsbridge.org/\" target=\"_blank\" style=\"color:#7F828E; text-decoration:underline;\">RailsBridge</a>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                      </table>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												</td>\r\n"
		+ "												</tr>\r\n"
		+ "												</table>\r\n"
		+ "												<![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" height=\"25\" width=\"100%\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td background=\"http://cdn-images.mailchimp.com/template_images/ux_reader/white_to_charcoal.jpg\" bgcolor=\"#7F828E\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "										  <v:rect xmlns:v=\"urn:schemas-microsoft-com:vml\" fill=\"true\" stroke=\"false\" style=\"mso-width-percent:1000;height:25px;\">\r\n"
		+ "											<v:fill type=\"tile\" src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/white_to_charcoal.jpg\" color=\"#7F828E\" />\r\n"
		+ "											<v:textbox inset=\"0,0,0,0\">\r\n"
		+ "										  <![endif]-->\r\n"
		+ "                      <div>\r\n"
		+ "                      </div>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "											</v:textbox>\r\n"
		+ "										  </v:rect>\r\n"
		+ "										  <![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "            <tr>\r\n"
		+ "              <td align=\"center\" valign=\"top\" id=\"emailFooter\">\r\n"
		+ "                <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"emailContainer\" style=\"max-width:640px;\">\r\n"
		+ "                  <tr>\r\n"
		+ "                    <td align=\"center\" valign=\"top\">\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												<table align=\"center\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"640\">\r\n"
		+ "												<tr>\r\n"
		+ "												<td align=\"center\" valign=\"top\">\r\n"
		+ "												<![endif]-->\r\n"
		+ "                      <table border=\"0\" cellpadding=\"10\" cellspacing=\"0\" width=\"100%\">\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" style=\"padding-top:20px;\">\r\n"
		+ "                            <a href=\"http://theuxnewsletter.com/\" target=\"_blank\"><img src=\"http://cdn-images.mailchimp.com/template_images/ux_reader/mcux_logo.png\" width=\"150\" style=\"height:auto !important;\"></a>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                        <tr>\r\n"
		+ "                          <td align=\"center\" valign=\"top\" class=\"footerContent\" style=\"color:#B1B5BC; font-family:Merriweather, Georgia, 'Times New Roman', Times, serif; font-size:14px; line-height:18px; padding-top:20px; padding-bottom:40px;\">\r\n"
		+ "                            <span style=\"color:#B1B5BC; text-decoration:none;\">512 Means St. NW,  Atlanta, GA 30318</span>\r\n"
		+ "                            <br>\r\n"
		+ "                            <a href=\"#\" style=\"color:#B1B5BC; text-decoration:underline;\">Unsubscribe</a>\r\n"
		+ "                          </td>\r\n"
		+ "                        </tr>\r\n"
		+ "                      </table>\r\n"
		+ "                      <!--[if gte mso 9]>\r\n"
		+ "												</td>\r\n"
		+ "												</tr>\r\n"
		+ "												</table>\r\n"
		+ "												<![endif]-->\r\n"
		+ "                    </td>\r\n"
		+ "                  </tr>\r\n"
		+ "                </table>\r\n"
		+ "              </td>\r\n"
		+ "            </tr>\r\n"
		+ "          </table>\r\n"
		+ "        </td>\r\n"
		+ "      </tr>\r\n"
		+ "    </table>\r\n"
		+ "  </center>\r\n"
		+ "</body>\r\n"
		+ "\r\n"
		+ "</html>";
}
